language: java
sudo: required
jdk: oraclejdk8
install:
- sudo apt-get update
- sudo apt-get install oracle-java8-installer

env:
  global:
  - BUILD_NUMBER=2.$TRAVIS_BUILD_NUMBER

script: bash ./jcompilo.sh

before_deploy:
# Create Tag!
- git config --global user.email "info@bodar.com"
- git config --global user.name "Build Server"
- git tag $BUILD_NUMBER -a -m "Build $BUILD_NUMBER"
- git push -q https://$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG --tags > /dev/null 2>&1

branches:
  # Stop tagging above from triggering another build (infinite)
  except:
  - /^[0-9].[0-9]*/

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file:
  - build/artifacts/*.jar
  - build/artifacts/*.pack.gz
  - build/artifacts/*.pom
  on:
    repo: $TRAVIS_REPO_SLUG
